package ba.unsa.etf.rpr.tutorijal03.Enum;

public enum Grad {
    SARAJEVO, TUZLA, ZENICA, BIHAC, BUGOJNO, ORASJE, LIVNO,
    MOSTAR, GORAZDE, POSUSJE, BRCKO, MRKONJIC, BANJA_LUKA, PRIJEDOR, DOBOJ, SAMAC, BIJELJINA,
    ZVORNIK, PALE, FOCA, TREBINJE
}
